api_prefix: /api/v1
api_version: v1.1.8
base_delay: 1 # seconds
env: local
loguru_format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <m>[</m>{thread}<m>]</m> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
loguru_level: debug
max_attempts: 5
max_file_size: 25 # 25 MB
max_part_size: 5 # 5 MB
openrouter_api_key: null
spool_max_size: 50 # 50 MB
