services:
  movie-log-backend:
    image: registry-1.docker.io/brokolee/movie-log-backend:prod
    build:
      context: .
      args:
        API_VERSION: v1.1.5
      dockerfile: Dockerfile.prod
    container_name: movie-log-backend-prod
    platform: linux/amd64
# sudo docker-compose -f docker-compose.prod.yaml build
# sudo docker run -p 8080:8080 --rm registry-1.docker.io/brokolee/movie-log-backend:prod
