services:
  movie-log-backend:
    image: registry-1.docker.io/brokolee/movie-log-backend:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    container_name: movie-log-backend-dev
    environment:
      ENV: "DEV"
      API_VERSION: "v1.1.8"
      LOGURU_LEVEL: "DEBUG"
      LOGURU_FORMAT: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <m>[</m>{process}<m>]</m> | <cyan>{name}</cyan><m>:</m><cyan>{function}</cyan><m>:</m><cyan>{line}</cyan> - <level>{message}</level>"
    env_file:
      - .env
    tty: true
    platform: linux/amd64
# sudo docker-compose -f docker-compose.dev.yaml build
# sudo docker run -p 8080:8080 --rm registry-1.docker.io/brokolee/movie-log-backend:dev
