services:
  movie-log-backend:
    image: registry-1.docker.io/brokolee/movie-log-backend:prod
    build:
      context: .
      dockerfile: prod.Dockerfile
    container_name: movie-log-backend-prod
    platform: linux/amd64
# sudo docker-compose -f prod-docker-compose.yaml build
# sudo docker run -p 8080:8080 --rm registry-1.docker.io/brokolee/movie-log-backend:prod
