-- Migration 012 (extraction_cache): content-addressed cache for ticket-
-- image extraction results. Same image bytes + same model + same prompt
-- version always produce the same extraction, so a repeat upload (a user
-- re-uploading their own ticket, or two different users photographing/
-- sharing the same physical ticket) can skip the LLM call entirely
-- instead of paying for and waiting on it again.
--
-- Keyed on (image_hash, model, prompt_version), not image_hash alone:
--   - model: different models can legitimately disagree on the same
--     image — a user with their own OpenRouter key requesting a premium
--     model shouldn't silently get served a result generated by the free
--     shared-tier model just because someone else uploaded the same
--     ticket first.
--   - prompt_version: a constant in services/extraction_cache.py, bumped
--     whenever llm/prompts/movie_metadata.py changes materially. This is
--     what keeps old cache entries from being served forever after a
--     prompt improvement — no TTL/expiry needed, a version bump
--     naturally makes old rows unreachable (they just stop matching, and
--     can be swept later if desired).
--
-- Not exposed through PostgREST to end users at all — accessed only via
-- the two RPCs below, called with the backend's own secret key, same
-- privileged-access pattern already used for increment_daily_usage
-- (services/quota.py). No RLS policies are added on purpose: RLS with
-- zero policies + no anon/authenticated grants means this table is
-- reachable only by the service_role executing these RPCs, never by a
-- caller's own token.

create table if not exists public.extraction_cache (
  image_hash text not null,
  model text not null,
  prompt_version text not null,
  metadata jsonb not null,
  hit_count int not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  last_hit_at timestamptz not null default timezone('utc', now()),
  primary key (image_hash, model, prompt_version)
);

alter table public.extraction_cache enable row level security;
revoke all on public.extraction_cache from anon, authenticated;

create or replace function public.get_cached_extraction(p_hash text, p_model text, p_prompt_version text)
returns jsonb
language sql
security definer
set search_path = public
as $$
  update public.extraction_cache
  set hit_count = hit_count + 1, last_hit_at = timezone('utc', now())
  where image_hash = p_hash and model = p_model and prompt_version = p_prompt_version
  returning metadata;
$$;

create or replace function public.upsert_extraction_cache(
  p_hash text, p_model text, p_prompt_version text, p_metadata jsonb
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.extraction_cache (image_hash, model, prompt_version, metadata)
  values (p_hash, p_model, p_prompt_version, p_metadata)
  on conflict (image_hash, model, prompt_version) do update
    set metadata = excluded.metadata, last_hit_at = timezone('utc', now());
$$;

revoke all on function public.get_cached_extraction(text, text, text) from public;
grant execute on function public.get_cached_extraction(text, text, text) to service_role;

revoke all on function public.upsert_extraction_cache(text, text, text, jsonb) from public;
grant execute on function public.upsert_extraction_cache(text, text, text, jsonb) to service_role;
